#ifndef DROIDS_H
#define DROIDS_H

#include <QObject>
#include <QThread>
#include "igame.h"
#include "animsequence.h"
#include <map>
#include <string>
#include <list>
#include <glm/glm.hpp>

// The Codegen's Parser
#include "parser/parser.h"
#include "parser/structures.h"

using namespace std;

namespace visualizer
{
    class Droids: public QThread, public AnimSequence, public IGame
    {
        struct Rect
        {
            int left;
            int top;
            int right;
            int bottom;
        };

        Q_OBJECT;
        Q_INTERFACES( visualizer::IGame );

        private:
            const float PI = 3.141592f;

			enum DROID_TYPE
			{
				DROID_CLAW = 0,
				DROID_ARCHER,
				DROID_REPAIRER,
				DROID_HACKER,
				DROID_TURRET,
				DROID_WALL,
				DROID_TERMINATOR,
				DROID_HANGAR
			};


        public: 
            Droids();
            ~Droids();

            PluginInfo getPluginInfo();
            void loadGamelog( std::string gamelog );

            void run();
            void setup();
            void destroy();

            void preDraw();
            void postDraw();

            void addCurrentBoard();
    
            map<string, int> programs;
            
            std::list<int> getSelectedUnits();

		private:
			void RenderGrid() const;

            void DrawHUD() const;

            void DrawScrapAmount() const;

            void UpdateHangarCount();

            glm::vec3 GetTeamColor(int owner) const;

            void PrepareUnits(const int& frameNum,Frame& turn, Frame& nextTurn);

            void PrepareTiles(const int& frameNum, Frame& turn, Frame& nextTurn);

            void PrepareLastFrame(const int& frameNum, Frame& turn);

            void GetSelectedRect(Rect &out) const;

            void ProcessInput();

            void pruneSelection();

            void DrawObjectSelection() const;

            void DrawBoxAroundObj(const parser::Mappable& obj, const glm::vec4& color) const;

            void DrawBoxAroundObj(const glm::vec2 topLeft, const int width, const int height, const glm::vec4 color) const;

            void DrawQuadAroundObj(const parser::Mappable& obj, const glm::vec4& color) const;

            void DrawQuadAroundObj(const glm::vec2 topLeft, const int width, const int height, const glm::vec4 color) const;

            std::list<IGUI::DebugOption> getDebugOptions();

        private:
            parser::Game *m_game;  // The Game Object from parser/structures.h that is generated by the Codegen
			int m_mapWidth;
			int m_mapHeight;
            bool m_suicide;

            int m_NumHangers;
            int m_Player0Hangars;
            int m_Player1Hangars;

            list<int> m_SelectedUnits;

            static const unsigned int GRID_OFFSET = 2;
    }; 

} // visualizer

#endif // DROIDS_H
